version: "3"
services:
  app:
    container_name: desafio-back-end
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: desafio-back-end-db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
